name: data-discovery-hub
new_cluster:
  spark_version: "13.3.x-scala2.12"
  node_type_id: "i3.xlarge"
  num_workers: 0
  spark_conf:
    "spark.databricks.cluster.profile": "singleNode"
    "spark.master": "local[*]"
  custom_tags:
    "ResourceClass": "SingleNode"

command:
  - "python"
  - "-m"
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port=8501"
  - "--server.address=0.0.0.0"
  - "--server.headless=true"
  - "--server.fileWatcherType=none"
  - "--browser.gatherUsageStats=false"

env:
  - name: "STREAMLIT_SERVER_HEADLESS"
    value: "true"
  - name: "STREAMLIT_SERVER_PORT"
    value: "8501"
  - name: "STREAMLIT_BROWSER_GATHER_USAGE_STATS"
    value: "false" 