# Production environment configuration
catalog: "leigh_robertson_demo"
bronze_schema: "bronze_noaa"
silver_schema: "silver_noaa_prod"
gold_schema: "gold_noaa_prod"

# Source tables
bronze_forecasts_table: "forecasts_streaming_demo"

# Streaming configuration
max_bytes_per_trigger: "1g"
checkpoint_location_base: "/mnt/production/checkpoints/weather_pipeline"

# Table properties
table_properties:
  quality: "silver"
  environment: "production"
  
# Data retention
retention_days: 365 