# Staging environment configuration
catalog: "leigh_robertson_demo"
bronze_schema: "bronze_noaa"
silver_schema: "silver_noaa_staging"
gold_schema: "gold_noaa_staging"

# Source tables
bronze_forecasts_table: "forecasts_streaming_demo"

# Streaming configuration
max_bytes_per_trigger: "5g"
checkpoint_location_base: "/tmp/checkpoints/weather_pipeline_staging"

# Table properties
table_properties:
  quality: "silver"
  environment: "staging"
  
# Data retention
retention_days: 60 